AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: {{ cookiecutter.project_name }}

Resources:

  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorld
      Description: Simple HelloWorld application
      Runtime: java11
      MemorySize: 512
      Handler: project.HelloWorld::handler
      CodeUri: target/lambda.zip
      Environment:
        Variables:
          LOCATIONS_TABLE: server=foo;db=bar